### ISSUE TITLE
How do you use a custom network for SafeService?

### ISSUE THREAD

**Issue by adriandelgg** [safe-global/safe-core-sdk#288]
I'm trying to use Hardhat local network to use SafeService with, but I don't know how I can make that happen since Safe doesn't have that as one of it's supported networks.

**Comment by germartinez** [comment]
Hello @adriandelgg,

There are a few instances of the [Safe Transaction Service](https://github.com/safe-global/safe-transaction-service) supporting different networks: https://docs.gnosis-safe.io/backend/available-services.

In order to run a local instance, you should run the service locally as well.

**Comment by adriandelgg** [comment]
> Hello @adriandelgg,
> 
> There are a few instances of the [Safe Transaction Service](https://github.com/safe-global/safe-transaction-service) supporting different networks: https://docs.gnosis-safe.io/backend/available-services.
> 
> In order to run a local instance, you should run the service locally as well.

Is there an article or video tutorial on how to do it on a local network?

**Comment by germartinez** [comment]
Not that I know.

I think this [README](https://github.com/safe-global/safe-transaction-service#setup-for-development) should be enough to run the service
