### ISSUE TITLE
Allow `SafeFactory.deploySafe` to use the L2 copy for proxy deployments on L1 chains

### ISSUE THREAD

**Issue by eli-lim** [safe-global/safe-core-sdk#492]
## Context / issue
- Feature request: allow `SafeFactory.deploySafe` to use the L2 copy for L1 proxy deployments

Why is this feature needed?
- To allow Safe wallets on L1s to emit events
- I'm trying to get Safe SDK to deploy an L2 safe proxy on Ethereum mainnet so that:
  - events are emitted
  - consistent address across L1s and L2s 

## Proposed solution
- Top-down: set `SafeFactory.#safeContract` to `protected`, allowing client code to override it with another implementation, OR

## Alternatives
- Bottom-up: deprecate `isL1SafeMasterCopy` in favour of a `copy = 'L1' | 'L2'` flag
  - This will eventually have to be demised

---

Caveat - I didn't spend a lot of time combing through the SDK repo in search of other alternatives

**Comment by dasanra** [comment]
@eli-lim thank you for your time opening this issue.

Currently it's possible to do what you describe by setting the `contractNetworks` property. There you can specify addresses to use in the SafeFactory in order to create a Safe overriding the default behavior of using L1 instance only when deploying on mainnet.

It's true that using this property is more complex than the solution you propose, but it's also true that the transaction service and hence the api-kit wouldn't be compatible with Safes deployed using that configuration on mainnet. For that reason we won't add this configuration as a default behavior on the SDK at this moment.
