### ISSUE TITLE
Upgrade @web3auth/base, critical empty idToken bug

### ISSUE THREAD

**Issue by myounatan** [safe-global/safe-core-sdk#535]
I recently found that the `idToken` field is empty when calling `await web3AuthModalPack.getUserInfo()` (like in this [safeAA example repo](https://github.com/safe-global/safe-core-sdk/blob/main/packages/auth-kit/example/src/App.tsx#L101))

The web3 auth forums recommend upgrading to at least 6.1.7 as this may solve the issue. (see here https://web3auth.io/community/t/getuserinfo-on-social-login-does-not-return-idtoken/4546/4)

The recommended package to upgrade is listed here:
https://github.com/safe-global/safe-core-sdk/blob/4d1c0e14630f951c2498e1d4dd521403af91d6e1/packages/auth-kit/package.json#L46C25-L46C25

The latest version (7.0.1) can be found here: https://www.npmjs.com/package/@web3auth/base

Is it possible to upgrade the web3auth packages to their latest versions? Thanks!

**Comment by yagopv** [comment]
Hey @myounatan, thanks !!

Can you use the [same versions](https://github.com/safe-global/safe-core-sdk/blob/69296ef3a528c806a58d03ef632b2b383369b029/packages/auth-kit/package.json#L46-L48) we are using in the auth-kit?  I know is a little behind but perhaps the bug is not there.

If you can't, we have plans to revamp the Web3Auth integration with something that fits better the use cases for Safe accounts so in this case, if needed, we recommend the direct usage of the @web3auth/modal package and the @safe-global/api-kit to retrieve the associated Safe accounts as [this is currenlty](https://github.com/safe-global/safe-core-sdk/blob/4d1c0e14630f951c2498e1d4dd521403af91d6e1/packages/auth-kit/src/AuthKitBasePack.ts#L53C1-L70C4) what the `Web3AuthModalPack` provide as output after the `signIn()`
