### ISSUE TITLE
How do I get the balance of an undeployed predictedSafeAddress

### ISSUE THREAD

**Issue by francelwebdev** [safe-global/safe-core-sdk#772]
Hi I've send ethers to an predictedSafeAddress and want to know balance on the predictedSafeAddress before deploy it. Please. Thanks

**Comment by dasanra** [comment]
You can use the protocolKit instance for that.

```
const protocolKit = await Safe.create({ ethAdapter, predictedSafe })

const balance = await protocolKit.getBalance()
```

`Safe.create()` will not deploy the Safe right away, this will happen the first time you execute a transaction.

**Comment by dasanra** [comment]
Could you please share the versions of the packages you are using?

Also could you share the code snippet? With the code I shared above, if you are using the latest versions you shouldn't be having such error.

**Comment by dasanra** [comment]
@francelwebdev could you also share the code fragment and also the chain you are using?

Thank you

**Comment by dasanra** [comment]
Ok, I see the issue now.

The initialization you are using inside `getBalance` is fine for a deployed Safe, but not for a Safe that wasn't deployed yet.

If you check carefully [in the docs](https://docs.safe.global/sdk/protocol-kit/reference/safe#create) in the `Safe.create()` you need to set a `predictedSafe` property instead of a `safeAddress`

This `predictedSafe` will look like the `safeAccountConfig` you used above for the `SafeFactory`

```
  const safeAccountConfig: SafeAccountConfig = {
    owners: [
        await owner1Signer.getAddress()
    ],
    threshold: 1,
    // ... (Optional params)
  }
  
  const protocolKit = await Safe.create({ ethAdapter, predictedSafe: safeAccountConfig })

  const balance = await protocolKit.getBalance()
```

This will make it work.
Also check that you are creating an instance of the `SafeApiKit` in the init function, which is not in use, but it's trying to use `mainnet` while you configured a `sepolia` RPC. This will cause problems also, so either remove it or set the correct `chainId`

**Comment by dasanra** [comment]
I'm not really sure if it's the expected balance. 
`1000000000000000n` is the value in wei, so it equals to `0.001`which it was the value in the account at some moment

**Comment by dasanra** [comment]
As no other feedback was given we will consider this issue as closed.

Feel free to open a new one if you have issues.
