### ISSUE TITLE
Display human readable amount in multisend transfers created from the API

### ISSUE THREAD

**Issue by ADumaine** [safe-global/safe-core-sdk#914]
## Context / issue

There is no display of the amount to send for a token transfer when a multisend transaction is built with the API and proposed to a Safe.  It only displays `amount(uint256):10000000000000000`. 

![image](https://github.com/user-attachments/assets/71786488-746f-486d-83c7-2fbb05fffff8)

If batch is built with the UI, the amount is displayed in each transaction

![image](https://github.com/user-attachments/assets/ebe29b95-e5c0-4a15-85e3-01746c39f316)

One of the points of having multiple signatures is to act as an approval process.  If a user cannot determine the amount of a transaction being sent, how are they expected to approve it?

## Proposed solution

Display the human readable amount to each recipient in a batch in the UI.  If certain data (e.g. decimals to convert the amount) are not available allow some meta data to be passed from the API.

## Alternatives

1. The design of the app being built is to only have the ability of a delegate or signer submit the transaction and have subsequent signers sign and execute through the Safe.  If the amounts cannot be understood by a Safe signer, the new application will have to be modified to add that functionality exposing additional safety concerns.

2. Add the ability to create and submit transactions to a batch from the API.  If there is already a way to do this, I missed it.

**Comment by katspaugh** [comment]
At the moment, we're not able to display amounts nicely for batches, or for any other non-transfer contract calls involving token amounts. The reason is that each protocol and contract has different parameter names for token address and amount, so it's not trivial to see from an arbitrary transaction which token it's operating on (and thus to get its decimals) and what the amount of that token is.

That said, we're looking into 3rd party human-readable APIs, so please stay tuned for updates. I'm closing this issue for now. Thanks for the feedback!
